name: lesson90_practice
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
